### ISSUE TITLE
Error : `active_admin_settings_page': uninitialized constant Options::VALID_OPTIONS

### ISSUE THREAD

**Issue by rtcoms** [artofhuman/activeadmin_settings_cached#35]
Using following versions of gem 

```
rails-settings-cached (0.6.6)
rails (= 4.2)
activeadmin (1.0.0.pre2)

activeadmin_settings_cached (2.0.0)
      activeadmin
      rails-settings-cached (>= 0.5.3)
```

Activeadmin setting page looks like this 

```
ActiveAdmin.register_page "Setting" do
  title = 'Settings'
  menu priority: 99

  active_admin_settings_page(
    title: title
  )
end
```

configuration

```
ActiveadminSettingsCached.configure do |config|
  config.model_name = 'SiteConfig'
end
```

Error I'm getting on starting rails server :

```
gems/activeadmin_settings_cached-2.0.0/lib/activeadmin_settings_cached/dsl.rb:14:in `active_admin_settings_page': uninitialized constant Options::VALID_OPTIONS (NameError)
	from /Users/rohittrivedi/work/professional/learninglabs/app/admin/setting.rb:5:in `block in <top (required)>'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/dsl.rb:15:in `instance_exec'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/dsl.rb:15:in `run_registration_block'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/namespace.rb:227:in `parse_page_registration_block'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/namespace.rb:63:in `register_page'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/application.rb:187:in `register_page'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin.rb:76:in `register_page'
	from /Users/rohittrivedi/work/professional/learninglabs/app/admin/setting.rb:1:in `<top (required)>'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/application.rb:215:in `block in load'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/error.rb:41:in `capture'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/application.rb:215:in `load'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/application.rb:207:in `block in load!'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/application.rb:207:in `each'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/application.rb:207:in `load!'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin/application.rb:229:in `routes'
	from /Users/rohittrivedi/.rvm/gems/ruby-2.2.1@learninglabs/bundler/gems/activeadmin-f7483e3b8fcd/lib/active_admin.rb:79:in `routes'
	from /Users/rohittrivedi/work/professional/learninglabs/config/routes.rb:243:in `block in <top (required)>'
```

**Comment by artofhuman** [comment]
Hi, plz try the latest version. This error should be fixed in 2.1.0 version
